### ISSUE TITLE
Building the Catalog

### ISSUE THREAD

**Issue by cktech529** [RallySoftware/app-catalog#194]
Hello,

I've pulled down the app catalog that uses SDK 2.1

When running

npm install (to pull down the dependencies) I get

pm install
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND npm.f4tech.com npm.f4tech.com:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /c4_working/app-catalog/npm-debug.log

Thoughts?

Thanks,

Chris

**Comment by krmorse** [comment]
This package relies on some libraries in our private npm registry that you won't have access to.  Is there a reason you need to build the entire catalog?

I'd just cd into the app directory you're interested in and use rally-app-builder to build and run it.

You also probably want to use the RallyApps/app-catalog fork instead of this one, since that is guaranteed to work with the latest 2.1 SDK.

**Comment by cktech529** [comment]
I am using: https://github.com/RallyApps/app-catalog
It says: These apps are built using App SDK 2.1. 

I just ran the builder in the folder and that worked... (Earlier I got NPM errors, but I had to reinstall thanks.)

Specially, I'd like to see how the following application works:
https://github.com/RallyApps/app-catalog/blob/master/src/apps/iterationsummary/IterationSummaryApp.js

Whenever I put a "requires" statement in a custom html application, I get 404 errors (can't find the file on the server...) I'd really like to make this application follow some sort of MVC pattern...

View: 
Define 'test.panel'
Extend ext's panel class
controller: 'view.controller'
requires: ['view.controller, ...],
...

Controller would then extend 
Deft.view.controller or something
have a control block
and it'd control view specific itemId's
handle the loaddata etc. etc.

Thoughts?

I see an early post about this using Deft back in 2012ish and then in 2014 something about using plugins...

Chris

**Comment by krmorse** [comment]
Sounds like you're on the right path then.  We investigated some Deft MVC for componentry in the App SDK but never really settled on a pattern we liked- Ext just really isn't set up for that sort of thing and it always just felt like the MVC was bolted on and you were awkwardly fighting the framework underneath.

Hopefully we'll get a version of our new react-based front-end framework released as an SDK sometime soon.  That has really nice separation of view from data/controller layers.  And you can plug redux into it, etc.

In the meantime though you can look at some of these components as examples:

Standard Deft MVC: 
- https://help.rallydev.com/apps/2.1/doc/source/TagChooser.html#Rally-ui-tagchooser-TagChooser

Using plugins:
- https://help.rallydev.com/apps/2.1/doc/source/CustomFilterRow.html#Rally-ui-filter-CustomFilterRow
- https://help.rallydev.com/apps/2.1/doc/source/CustomFilterRowController.html#Rally-ui-filter-plugin-CustomFilterRowController

**Comment by cktech529** [comment]
Thanks,

When I would use the requires controller configs, it would throw errors on loading the application (where it couldn't find my controller on the server...)

I'll try and duplicate, maybe I'm doing something incorrectly.

**Comment by cktech529** [comment]
IterationSummaryApp.js
_onBulkUpdate: function(records) {
            if(**_.any**(records, this._shouldUpdate, this)) {  // I'm not seeing where _.any is defined...
                this._addContent();
            }
        },

**Comment by krmorse** [comment]
lodash and Deft are both included in the sdk.  you can see the full list of embedded 3rd party libs here: https://help.rallydev.com/apps/2.1/doc/#!/guide/third_party_libs

**Comment by cktech529** [comment]
Thanks, sorry to waste your time on that one (I totally missed that page..)  ---

Lastly,

On a Ext.define('CustomApp', {
    extend: 'Rally.app.TimeboxScopedApp',
    scopeType: 'release',

...

Is there a config or a way to STOP the Release Combo Box to Autoload the current iteration an allow for the user BEFORE the application loads, to select which PSI/ Release they want to load?

I'd like to somehow override the combo box (or push something to the combo box on the TimeboxScopedApp so that it doesn't load on application startup.... Thoughts?

We're also seeing issues if the user selects  release PSI 12 say, then while the application is loading selects PSI 13, errors with the data/ load... 

Thanks again!

**Comment by cktech529** [comment]
Hello again,

Any way to get <script src="https://code.highcharts.com/modules/offline-exporting.js" working with Rally? 

It'd be great to be able to export highcharts (without having to do anything serverside) but when I load the above script, rally fails because that script makes NON secure connections...

Thoughts?

Anything built in (i can't find it) to the rally sdk to export charts?

**Comment by cktech529** [comment]
Whenever I declare a view/ controller (where the view requires the controller and has the controller property set to the controller I get the following after running the rally-app-builder build... 

<img width="993" alt="screen shot 2016-07-27 at 9 36 43 pm" src="https://cloud.githubusercontent.com/assets/6800679/17198321/426ee3d8-5442-11e6-9267-23d6423118b2.png">

How would I on a custom application that extends: 'Rally.app.TimeboxScopedApp', use MVC like Rally.ui.tagchooser.TagChooser ? Thanks again, Chris.

**Comment by krmorse** [comment]
That requires error is most likely because you have your files in the incorrect dependency order in your config.json.  Is your ObjectivesView.js listed before your App.js?

**Comment by krmorse** [comment]
That offline export highcharts feature is cool.  Not sure if it (v4.2.5) is compatible with our version of highcharts (3.0.10) or not.  Unfortunately there's nothing we can do about the http call.  You should try to follow up with the highcharts folks to see what they can do there...

**Comment by krmorse** [comment]
Rally.app.TimeboxScopedApp is very much designed to load a timebox on startup, so you'll probably have a bad time trying to change that.  Your best bet is to create an app that just extends from Rally.app.App and render your own Iteration or Release combobox with storeConfig: { autoLoad: false }

**Comment by krmorse** [comment]
I think I addressed all your questions- it's a little hard to tell since we've deviated from the original issue quite a bit.  In the future please use our [stackoverflow](http://stackoverflow.com/questions/tagged/rally) to ask questions so the entire community can benefit from the wisdom!

**Comment by cktech529** [comment]
Thanks Krmorse,

Yeah pardon the deviation here! (I didn't know about this Stackoverflow page..) 
Any chance on the next SDK release, highcharts could be updated (and pull this offline export in :)?) 
I'll test the import dependency order, I believe I had app.js first... 

Chris

**Comment by krmorse** [comment]
Unfortunately the 2.1 release of the App SDK is the last in that series.  We are working on a new react based 3.x version, which I would imagine will include an updated version of highcharts.  I can't make any promises or mention timelines, but it seems like this will happen at some point...

**Comment by cktech529** [comment]
Thanks,

Just saw this reply. If you ever need beta testers for that react API, heck
pre-heat, I am very curious :).

**Comment by cktech529** [comment]
The 'http' fix was simple actually: 

 exporting: {
                chartOptions: { // specific options for the exported image
                    plotOptions: {
                        series: {
                            dataLabels: {
                                enabled: true
                            }
                        }
                    }
                },
                scale: 3,
                **_url: 'https://export.highcharts.com'_**
            },
